### ISSUE TITLE
GAME - This little item still in the loot table

### ISSUE THREAD

**Issue by soyochanz** [QI-Software/deadmatterpublic#117]
Idk if it will do something in the future but right now im not sure if it should be here

![icons](https://github.com/QI-Software/deadmatterpublic/assets/156482721/e30a4894-6707-422c-aa24-11a7da9e8a8b)

**Comment by johnnyguitarFP** [comment]
Please keep the item in your inventory and send me a copy of your save file.

**Comment by soyochanz** [comment]
Fuck i already die... dont worry ill find it again
