### ISSUE TITLE
MAP - Red lights issue

### ISSUE THREAD

**Issue by soyochanz** [QI-Software/deadmatterpublic#123]
There are some red lights that shouldn't be there
![20240301200614_1](https://github.com/QI-Software/deadmatterpublic/assets/156482721/1585f2ac-2d7e-4cee-af12-41cfc04c79ed)
![20240301200628_1](https://github.com/QI-Software/deadmatterpublic/assets/156482721/11bb67e0-8a46-444b-bc00-ca2bfb83e8e3)
![20240301200656_1](https://github.com/QI-Software/deadmatterpublic/assets/156482721/4868b84a-54d1-4759-a6fb-8ef8ad24159e)

**Comment by johnnyguitarFP** [comment]
This is a bug with Unreal Engine and Lumen.
