### ISSUE TITLE
access to steam copy revoked for no reason.

### ISSUE THREAD

**Issue by Shawnx17** [QI-Software/deadmatterpublic#153]
Redeemed my copy for the beta access from the QI website. I let it install and it seems about an hour later roughly my key is revoked with no rhyme or reason. Backed the " This is no dream! " tier and would like access to my game back if you dont mind. Thanks 
![Screenshot 2024-03-05 222344](https://github.com/QI-Software/deadmatterpublic/assets/162401733/81ba556c-411e-4bd8-8dae-9333b84c245e)

**Comment by johnnyguitarFP** [comment]
https://www.new.playdeadmatter.com/news/key-redemption-issues

Keys got mixed up and an issue has occurred, we're working on getting it resolved.
