### ISSUE TITLE
Random Floating light switch

### ISSUE THREAD

**Issue by jackjohns0n** [QI-Software/deadmatterpublic#182]
![Untitled](https://github.com/QI-Software/deadmatterpublic/assets/50780730/f177841a-5f98-42dc-bcf8-10aec4941989)
![Untitled1](https://github.com/QI-Software/deadmatterpublic/assets/50780730/29da7927-d95d-4429-8a38-3c4a8fa18fae)

Dont know how to get my position in game but its in the bathrooms in the campground around dead mans flats

**Comment by QI-Vitka** [comment]
Would this be the campgrounds closer to the River Rafting Centre (Garry's Cabin Co), or is it closer to the town itself? Having a little trouble tracking this specific bathroom down from the close up shot.

**Comment by jackjohns0n** [comment]
uh.....i dont know?

**Comment by QI-Vitka** [comment]
found and fixed!
