### ISSUE TITLE
Floating,Clipping,Invisible Stuff

### ISSUE THREAD

**Issue by kleber0815** [QI-Software/deadmatterpublic#185]
Invisble Car + Terrain Issues:

-83144.532680 660933.751071 -34174.261731
![20240307113113_1](https://github.com/QI-Software/deadmatterpublic/assets/78033720/de04fafc-f29d-41c7-8626-2a6988219b54)

Railing Placement:

-231008.371664 673860.285746 -34562.519339
![20240307114028_1](https://github.com/QI-Software/deadmatterpublic/assets/78033720/6503197d-9633-4ba9-87ef-114d772861d8)

Car Clipping in Ground:

-260936.642525 676436.704130 -32635.759451
![20240307114119_1](https://github.com/QI-Software/deadmatterpublic/assets/78033720/020cafcd-abe7-4942-856f-a09eba34f0b1)

Floating Window:

-646313.438583 202572.265501 -28096.227791
![20240308094508_1](https://github.com/QI-Software/deadmatterpublic/assets/78033720/0a1055cc-edb8-4663-b844-8a491283d4fa)

Train no on Tracks

-615125.377527 233004.263075 -28690.604975
![20240308135157_1](https://github.com/QI-Software/deadmatterpublic/assets/78033720/2d9fc484-068b-41d6-b726-6528851313d8)

**Comment by QI-Vitka** [comment]
next commit clears these minus train (it's supposed to be a powerplant for the settlement + not sure if real trains will be using this track or not when they're implemented + I'm too afraid to rebake the cable right now)
