### ISSUE TITLE
Invisible car?

### ISSUE THREAD

**Issue by jackjohns0n** [QI-Software/deadmatterpublic#200]
![Untitled](https://github.com/QI-Software/deadmatterpublic/assets/50780730/da6c091d-827c-4b09-a413-15e1a385a316)
Here is my position using the getpos command
-66864.028193 647750.586137 -34620.491730
Single Player, main branch.  I'm thinking there is supposed to be a vehicle under that tarp?

**Comment by kleber0815** [comment]
correct, already reported another Location which got fixed + more Locations i randomly found on the nightly we're also fixed, this one is propably also already fixed on nightly - i can Check that later if no one else is faster.

### **Still invisible on the current Nightly!**
