### ISSUE TITLE
Basebuilding - A couple of issues

### ISSUE THREAD

**Issue by soyochanz** [QI-Software/deadmatterpublic#25]
It seems that the door upgraded to metal has less health points than the standard one. (I cannot confirm it but looks like)

The Nera Barricade and Newspaper window barricades do not require you to have the components to build them. 
For Metal Barricade and Wood Barricade, the option to add ingredients does not appear

**Comment by johnnyguitarFP** [comment]
I'll address the issues with the newspaper and nera barricade, let me know if the metal barricade and wood barricade are still messed up once I push the next build.

**Comment by soyochanz** [comment]
> I'll address the issues with the newspaper and nera barricade, let me know if the metal barricade and wood barricade are still messed up once I push the next build.

Yes, still the issue, i cant still building the metal and wood barricade on windfows
