### ISSUE TITLE
Inventory - Icons issue

### ISSUE THREAD

**Issue by soyochanz** [QI-Software/deadmatterpublic#32]
Sometimes, when you loot items like weapons and clothing, if you move them to another position with R, they bug out and appear larger (only happens sometimes
(Check the gloves)
![20240114022926_1](https://github.com/QI-Software/deadmatterpublic/assets/156482721/8fd2d212-d13a-456e-81d9-c5a37aebfd00)

**Comment by soyochanz** [comment]
![20240115065503_1](https://github.com/QI-Software/deadmatterpublic/assets/156482721/93f5abb2-5a13-4e97-8479-7b872813df9e)
One more example (The hammer)

**Comment by johnnyguitarFP** [comment]
Repro steps involve shift clicking
