### ISSUE TITLE
Map -  Bunker second entrance 

### ISSUE THREAD

**Issue by soyochanz** [QI-Software/deadmatterpublic#43]
The sencond entrance to the bunker seems to be bugged at certain distance

![20240114113841_1](https://github.com/QI-Software/deadmatterpublic/assets/156482721/b63e6bf0-c89f-4d76-b684-0216c898d388)
![20240114113852_1](https://github.com/QI-Software/deadmatterpublic/assets/156482721/b1613c56-051d-47ae-95d7-84bfca754b3c)

**Comment by johnnyguitarFP** [comment]
Missing HLODs
