### ISSUE TITLE
House walls are gone.

### ISSUE THREAD

**Issue by TossedGuitar** [QI-Software/deadmatterpublic#49]
Some of the houses don't have walls.
![20240124124454_1](https://github.com/QI-Software/deadmatterpublic/assets/156388893/1565d78d-b98d-44f8-82fc-8b2823314e64)
![20240124124427_1](https://github.com/QI-Software/deadmatterpublic/assets/156388893/bdc9397f-6e01-4339-bfe2-c59d5a8b2677)
![20240124124431_1](https://github.com/QI-Software/deadmatterpublic/assets/156388893/500349a7-259a-4f58-b257-e14d66935bff)

**Comment by johnnyguitarFP** [comment]
Should be fixed. Reopen if not.
