### ISSUE TITLE
MAP - Duplicated object

### ISSUE THREAD

**Issue by soyochanz** [QI-Software/deadmatterpublic#54]
In this new area there is a hockey stick that you can pick it twice since is duplicated in the same possition
![20240202105216_1](https://github.com/QI-Software/deadmatterpublic/assets/156482721/cb4a0d9d-fabb-4bac-bdf0-414f3037e9df)
![20240202105412_1](https://github.com/QI-Software/deadmatterpublic/assets/156482721/fe8afbdd-9068-4c1f-8df0-b0ff7eaab64b)

**Comment by soyochanz** [comment]
same with this box of nails
![20240202105620_1](https://github.com/QI-Software/deadmatterpublic/assets/156482721/3b263e1a-89ae-42f0-907b-af412b58de25)

**Comment by johnnyguitarFP** [comment]
should be fixed in the next update
