### ISSUE TITLE
MAP - Low FPS in dominion

### ISSUE THREAD

**Issue by soyochanz** [QI-Software/deadmatterpublic#57]
In my case is the worst optimized area in the map, most when im close to the traders.

![20240202110318_1](https://github.com/QI-Software/deadmatterpublic/assets/156482721/960b8600-7f98-4853-ac71-da0fb5976b74)

**Comment by KrystofSliva** [comment]
Yes, true. Dominion really has bad FPS. @johnnyguitarFP remove the label pls

- ToustCZ
