### ISSUE TITLE
COOKING - Cooking a 4 stack have to be a bug

### ISSUE THREAD

**Issue by soyochanz** [QI-Software/deadmatterpublic#60]
When cooking, it allows you to cook a stack of 4 meats instead of one by one
![20240206173534_1](https://github.com/QI-Software/deadmatterpublic/assets/156482721/7d4154e9-76a0-48b5-980c-13d2b6768ecb)

**Comment by johnnyguitarFP** [comment]
Not a bug, this is just a side effect of how stack text is formatted.
