### ISSUE TITLE
BASEBUILDING - Doors opening when pressing V

### ISSUE THREAD

**Issue by soyochanz** [QI-Software/deadmatterpublic#69]
All barricaded doors open automatically when I enable construction mode
![20240208142431_1](https://github.com/QI-Software/deadmatterpublic/assets/156482721/d6c2a7b6-567d-4885-96c2-043b70d1ff28)
![20240208142432_1](https://github.com/QI-Software/deadmatterpublic/assets/156482721/caae4a2d-7380-42b7-8190-4db354511e8d)

**Comment by johnnyguitarFP** [comment]
These are removed until I find a better way to handle them.
