### ISSUE TITLE
Pistol not showing while using flashlight

### ISSUE THREAD

**Issue by soyochanz** [QI-Software/deadmatterpublic#74]
![20240220153628_1](https://github.com/QI-Software/deadmatterpublic/assets/156482721/8b1a4dcb-4099-48b5-b4ff-7d181d902d91)

This is in Multiplayer

**Comment by itsFiftyy** [comment]
![image](https://github.com/QI-Software/deadmatterpublic/assets/85461840/244ee291-05b0-4694-a55d-0f51f21a95f6)
can confirm

**Comment by itsFiftyy** [comment]
its probs related to the fix you did for pistol flashlight combo @johnnyguitarFP
