### ISSUE TITLE
ICONS - Icons not loading properly

### ISSUE THREAD

**Issue by soyochanz** [QI-Software/deadmatterpublic#75]
![20240223221936_1](https://github.com/QI-Software/deadmatterpublic/assets/156482721/8ef516a2-2e59-4275-83b1-221de8781abf)

Tested in build 9634 - Build #150

**Comment by johnnyguitarFP** [comment]
This is actually a separate issue from other bugs in the Item Icon system, chopping trees and dropping items seems to also be affected. Using the ESP we can see that while the items exist, they're not having their mesh setup correctly.
